package com.evergreen.distribucion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CanalComercializacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalComercializacionAllPropertiesEquals(CanalComercializacion expected, CanalComercializacion actual) {
        assertCanalComercializacionAutoGeneratedPropertiesEquals(expected, actual);
        assertCanalComercializacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalComercializacionAllUpdatablePropertiesEquals(
        CanalComercializacion expected,
        CanalComercializacion actual
    ) {
        assertCanalComercializacionUpdatableFieldsEquals(expected, actual);
        assertCanalComercializacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalComercializacionAutoGeneratedPropertiesEquals(
        CanalComercializacion expected,
        CanalComercializacion actual
    ) {
        assertThat(actual)
            .as("Verify CanalComercializacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalComercializacionUpdatableFieldsEquals(CanalComercializacion expected, CanalComercializacion actual) {
        assertThat(actual)
            .as("Verify CanalComercializacion relevant properties")
            .satisfies(a -> assertThat(a.getIdentificador()).as("check identificador").isEqualTo(expected.getIdentificador()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalComercializacionUpdatableRelationshipsEquals(
        CanalComercializacion expected,
        CanalComercializacion actual
    ) {
        // empty method
    }
}
