package com.evergreen.distribucion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmpaqueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpaqueAllPropertiesEquals(Empaque expected, Empaque actual) {
        assertEmpaqueAutoGeneratedPropertiesEquals(expected, actual);
        assertEmpaqueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpaqueAllUpdatablePropertiesEquals(Empaque expected, Empaque actual) {
        assertEmpaqueUpdatableFieldsEquals(expected, actual);
        assertEmpaqueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpaqueAutoGeneratedPropertiesEquals(Empaque expected, Empaque actual) {
        assertThat(actual)
            .as("Verify Empaque auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpaqueUpdatableFieldsEquals(Empaque expected, Empaque actual) {
        assertThat(actual)
            .as("Verify Empaque relevant properties")
            .satisfies(a -> assertThat(a.getIdentificador()).as("check identificador").isEqualTo(expected.getIdentificador()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getTamanio()).as("check tamanio").isEqualTo(expected.getTamanio()))
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a -> assertThat(a.getTiempoMinutos()).as("check tiempoMinutos").isEqualTo(expected.getTiempoMinutos()))
            .satisfies(a -> assertThat(a.getFechaRealizacion()).as("check fechaRealizacion").isEqualTo(expected.getFechaRealizacion()))
            .satisfies(a -> assertThat(a.getResponsable()).as("check responsable").isEqualTo(expected.getResponsable()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpaqueUpdatableRelationshipsEquals(Empaque expected, Empaque actual) {
        assertThat(actual)
            .as("Verify Empaque relationships")
            .satisfies(a -> assertThat(a.getPedido()).as("check pedido").isEqualTo(expected.getPedido()));
    }
}
