package com.evergreen.distribucion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PedidoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAllPropertiesEquals(Pedido expected, Pedido actual) {
        assertPedidoAutoGeneratedPropertiesEquals(expected, actual);
        assertPedidoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAllUpdatablePropertiesEquals(Pedido expected, Pedido actual) {
        assertPedidoUpdatableFieldsEquals(expected, actual);
        assertPedidoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAutoGeneratedPropertiesEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoUpdatableFieldsEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido relevant properties")
            .satisfies(a -> assertThat(a.getIdentificador()).as("check identificador").isEqualTo(expected.getIdentificador()))
            .satisfies(a -> assertThat(a.getFechaEntrada()).as("check fechaEntrada").isEqualTo(expected.getFechaEntrada()))
            .satisfies(a -> assertThat(a.getFechaSalida()).as("check fechaSalida").isEqualTo(expected.getFechaSalida()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoUpdatableRelationshipsEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido relationships")
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()))
            .satisfies(a -> assertThat(a.getProductos()).as("check productos").isEqualTo(expected.getProductos()))
            .satisfies(a ->
                assertThat(a.getCanalComercializacion()).as("check canalComercializacion").isEqualTo(expected.getCanalComercializacion())
            )
            .satisfies(a -> assertThat(a.getTransporte()).as("check transporte").isEqualTo(expected.getTransporte()));
    }
}
