package com.evergreen.distribucion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SeparacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeparacionAllPropertiesEquals(Separacion expected, Separacion actual) {
        assertSeparacionAutoGeneratedPropertiesEquals(expected, actual);
        assertSeparacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeparacionAllUpdatablePropertiesEquals(Separacion expected, Separacion actual) {
        assertSeparacionUpdatableFieldsEquals(expected, actual);
        assertSeparacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeparacionAutoGeneratedPropertiesEquals(Separacion expected, Separacion actual) {
        assertThat(actual)
            .as("Verify Separacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeparacionUpdatableFieldsEquals(Separacion expected, Separacion actual) {
        assertThat(actual)
            .as("Verify Separacion relevant properties")
            .satisfies(a -> assertThat(a.getIdentificador()).as("check identificador").isEqualTo(expected.getIdentificador()))
            .satisfies(a -> assertThat(a.getLote()).as("check lote").isEqualTo(expected.getLote()))
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a -> assertThat(a.getFechaRealizacion()).as("check fechaRealizacion").isEqualTo(expected.getFechaRealizacion()))
            .satisfies(a -> assertThat(a.getUbicacion()).as("check ubicacion").isEqualTo(expected.getUbicacion()))
            .satisfies(a -> assertThat(a.getResponsable()).as("check responsable").isEqualTo(expected.getResponsable()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeparacionUpdatableRelationshipsEquals(Separacion expected, Separacion actual) {
        assertThat(actual)
            .as("Verify Separacion relationships")
            .satisfies(a -> assertThat(a.getPedido()).as("check pedido").isEqualTo(expected.getPedido()));
    }
}
