package com.evergreen.distribucion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransporteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransporteAllPropertiesEquals(Transporte expected, Transporte actual) {
        assertTransporteAutoGeneratedPropertiesEquals(expected, actual);
        assertTransporteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransporteAllUpdatablePropertiesEquals(Transporte expected, Transporte actual) {
        assertTransporteUpdatableFieldsEquals(expected, actual);
        assertTransporteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransporteAutoGeneratedPropertiesEquals(Transporte expected, Transporte actual) {
        assertThat(actual)
            .as("Verify Transporte auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransporteUpdatableFieldsEquals(Transporte expected, Transporte actual) {
        assertThat(actual)
            .as("Verify Transporte relevant properties")
            .satisfies(a -> assertThat(a.getIdentificador()).as("check identificador").isEqualTo(expected.getIdentificador()))
            .satisfies(a -> assertThat(a.getTipoTransporte()).as("check tipoTransporte").isEqualTo(expected.getTipoTransporte()))
            .satisfies(a -> assertThat(a.getMatricula()).as("check matricula").isEqualTo(expected.getMatricula()))
            .satisfies(a -> assertThat(a.getCapacidadKg()).as("check capacidadKg").isEqualTo(expected.getCapacidadKg()))
            .satisfies(a -> assertThat(a.getCapacidadM3()).as("check capacidadM3").isEqualTo(expected.getCapacidadM3()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFechaAsignacion()).as("check fechaAsignacion").isEqualTo(expected.getFechaAsignacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransporteUpdatableRelationshipsEquals(Transporte expected, Transporte actual) {
        // empty method
    }
}
